[hooks]
enter = "mise i -q"

[settings]
experimental = true
lockfile = true

[tools]
cosign = "latest"
go = "latest"
"go:github.com/tailscale/depaware" = "latest"
"go:go.uber.org/nilaway/cmd/nilaway" = "latest"
"go:golang.org/x/tools/cmd/eg" = "latest"
golangci-lint = "latest"
slsa-verifier = "latest"
"ubi:ast-grep/ast-grep" = "latest"
