[hooks]
enter = "mise i -q"

[settings]
experimental = true
lockfile = true

[tasks.ast-grep]
description = "Run ast-grep rules against the library source code."
hide = true
run = "ast-grep scan"
depends = "build"
# If this task and test run at the same time, force eg to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.ast-grep-test]
description = "Run the tests for the ast-grep rules."
hide = true
run = "ast-grep test"
sources = ["sgconfig.yml", "sg/**"]
outputs = { auto = true }
# If this task and test run at the same time, force it to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.build]
description = "Build the library source code."
run = "go build ./..."
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
depends = ["go-sanity-check"]
alias = "b"

[tasks.check]
description = "Run all linters and tests against the library source code."
depends = ["lint", "test"]
alias = "c"

[tasks.default]
depends = ["check"]

[tasks.depaware]
description = "Check that no Go package dependencies changed unexpectedly."
hide = true
run = "go run internal/tasks.go depaware"
depends = ["build"]
sources = ["go.mod", "go.sum", "**/*.go", "**/depaware.txt"]
outputs = { auto = true }

[tasks.eg]
description = "Check that the library source code is already refactored according to the eg templates."
hide = true
run = "go run internal/tasks.go eg"
depends = ["build"]
sources = ["go.mod", "go.sum", "**/*.go", "eg/*.template"]
outputs = { auto = true }
# If this task and test run at the same time, force it to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.fix]
description = "Automatically fix as many lint errors as possible."
depends = ["build"]
run = [
  "ast-grep scan --update-all",
  "go run internal/tasks.go eg-fix",
  "golangci-lint run --fix",
  "go run internal/tasks.go depaware-fix",
]
alias = "f"

[tasks.go-sanity-check]
description = "Run various Go-related quick sanity checks against the project"
hide = true
run = [
  "go mod verify",
  "go mod download",
  "go mod tidy",
  "git diff --exit-code -- go.mod go.sum",
]

[tasks.golangci-lint]
description = "Check that no problems are found when running the linters defined in .golangci.yml against the library source code."
hide = true
run = "golangci-lint run"
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
# If this task and test run at the same time, force it to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.lint]
description = "Check the library source code for problems."
hide = true
depends = [
  "ast-grep",
  "ast-grep-test",
  "depaware",
  "eg",
  "go-sanity-check",
  "golangci-lint",
]

[tasks.nilaway]
description = "Check that no common sources of nil pointer dereferences can occur in the library source code."
hide = true
run = "nilaway -include-pkgs github.com/jbduncan/go-containers ./..."
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
# If this task and test run at the same time, force it to run last to improve
# diagnostics in case of test compilation failures.
wait_for = ["test"]

[tasks.test]
description = "Run tests for the library source code."
run = "go test -shuffle=on -race ./..."
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "t"

[tasks.test-rerun]
description = "Run tests for the library source code, even if no changes have been made."
run = "go test -shuffle=on -race ./..."
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
alias = "tr"

[tasks.update-versions]
description = "Update the versions of all tools and dependencies."
run = [
  "mise x -- go get -u -t ./...",
  "mise up"
]
alias = "u"

[tools]
# cosign is used by mise itself to download tools more securely
cosign = "latest"
go = "latest"
"go:github.com/tailscale/depaware" = "b748de0"
"go:go.uber.org/nilaway/cmd/nilaway" = "ba14292"
"go:golang.org/x/tools/cmd/eg" = "latest"
golangci-lint = "latest"
# slsa-verifier is used by mise itself to download tools more securely
slsa-verifier = "latest"
"ubi:ast-grep/ast-grep" = "latest"
