# $schema: https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/project.json
# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/project.json
ruleDirs:
- ./sg/rules
testConfigs:
- testDir: ./sg/rule-tests
