// Code generated by "stringer -type=DirectionMode"; DO NOT EDIT.

package graphtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Directed-0]
	_ = x[Undirected-1]
}

const _DirectionMode_name = "DirectedUndirected"

var _DirectionMode_index = [...]uint8{0, 8, 18}

func (i DirectionMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DirectionMode_index)-1 {
		return "DirectionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DirectionMode_name[_DirectionMode_index[idx]:_DirectionMode_index[idx+1]]
}
