// Code generated by "stringer -type=Mutability"; DO NOT EDIT.

package graphtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mutable-0]
	_ = x[Immutable-1]
}

const _Mutability_name = "MutableImmutable"

var _Mutability_index = [...]uint8{0, 7, 16}

func (i Mutability) String() string {
	if i < 0 || i >= Mutability(len(_Mutability_index)-1) {
		return "Mutability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mutability_name[_Mutability_index[i]:_Mutability_index[i+1]]
}
