// Code generated by "stringer -type=mutability"; DO NOT EDIT.

package graphtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mutable-0]
	_ = x[readOnly-1]
}

const _mutability_name = "mutablereadOnly"

var _mutability_index = [...]uint8{0, 7, 15}

func (i mutability) String() string {
	if i < 0 || i >= mutability(len(_mutability_index)-1) {
		return "mutability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mutability_name[_mutability_index[i]:_mutability_index[i+1]]
}
