// Code generated by "stringer -type=SelfLoopsMode"; DO NOT EDIT.

package graphtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllowsSelfLoops-0]
	_ = x[DisallowsSelfLoops-1]
}

const _SelfLoopsMode_name = "AllowsSelfLoopsDisallowsSelfLoops"

var _SelfLoopsMode_index = [...]uint8{0, 15, 33}

func (i SelfLoopsMode) String() string {
	if i < 0 || i >= SelfLoopsMode(len(_SelfLoopsMode_index)-1) {
		return "SelfLoopsMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SelfLoopsMode_name[_SelfLoopsMode_index[i]:_SelfLoopsMode_index[i+1]]
}
