#!/usr/bin/env bash
#MISE description="Check that the library source code is already refactored according to the eg templates."
#MISE hide=true
#MISE depends=["build"]

set -eo pipefail

command -v go >/dev/null 2>&1 || { echo >&2 "go is not on the PATH. Aborting."; exit 1; }

go run mise/tasks/tasks.go eg
